name: snakemake_binomial_regression
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.10.4
  - pip=23.2.1
  - snakemake=7.32.2
  - anndata=0.10.9
  - pandas==2.1.1
  - numpy==1.26.4
  - r-base=4.3.3
  - r-matrix=1.6_5
  - r-optparse=1.7.5
  - r-tidyverse=2.0.0
  - r-data.table=1.15.4
  - r-lme4=1.1_35.5
  - r-dosnow=1.0.20
  - r-domc=1.3.8
  - r-doparallel=1.0.17
  - r-hdf5r=1.3.11
  - r-devtools
  - bioconductor-qvalue=2.34.0
  - r-tmb=1.9.14
  - r-gamlss=5.4_20
  - r-fitdistrplus=1.1_11
  - r-ashr=2.2_63